# Generated by Django 6.0.5 on 2026-06-01 20:02

from django.db import migrations


def populate_default_categories(apps, schema_editor):
    Category = apps.get_model('expenses', 'Category')
    defaults = [
        {"name": "Food", "icon": "Utensils"},
        {"name": "Transport", "icon": "Car"},
        {"name": "Entertainment", "icon": "Film"},
        {"name": "Shopping", "icon": "ShoppingBag"},
        {"name": "Utilities", "icon": "Zap"},
        {"name": "Housing", "icon": "Home"},
        {"name": "Other", "icon": "Tag"},
    ]
    for cat in defaults:
        Category.objects.get_or_create(
            name=cat["name"], 
            defaults={"icon": cat["icon"], "is_default": True}
        )

class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_category_expense_category'),
    ]

    operations = [
        migrations.RunPython(populate_default_categories, migrations.RunPython.noop),
    ]
