# Generated by Django 6.0.6 on 2026-07-02 19:46

import pgvector.django.vector
from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_populate_default_categories'),
    ]

    operations = [
        VectorExtension(),
        migrations.AddField(
            model_name='expense',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
