# Generated by Django 6.0.6 on 2026-07-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aichatmessage',
            name='settlement_payload',
            field=models.JSONField(blank=True, help_text='Structured JSON of a proposed settlement, if applicable.', null=True),
        ),
    ]
