# Generated by Django 6.0.6 on 2026-07-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_aichatmessage_settlement_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='aichatmessage',
            name='is_actioned',
            field=models.BooleanField(default=False, help_text='True if the user has already confirmed or acted on this AI proposal.'),
        ),
    ]
