# Generated by Django 6.0.6 on 2026-07-04 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_aichatmessage_is_actioned'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIDashboardHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prompt', models.TextField(help_text='The natural language prompt that generated this dashboard.')),
                ('dashboard_data', models.JSONField(help_text='The structured layout and widget data for the dashboard.')),
                ('user', models.ForeignKey(help_text='The user who generated this dashboard.', on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Dashboard History',
                'verbose_name_plural': 'AI Dashboard Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
