# Generated by Django 6.0.5 on 2026-05-31 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='avatar',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
