# Generated by Django 6.0.5 on 2026-05-31 17:12

import apps.groups.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='settings',
            field=models.JSONField(blank=True, default=apps.groups.models.get_default_group_settings),
        ),
    ]
